In [33]:
import pandas as pd
import numpy as np

# Question 1 Version of Numpy

In [34]:
print(np.__version__)

1.19.2


## Question 2 Version of Pandas 

In [35]:
print(pd.__version__)

1.2.3


## Question 3

In [36]:
df=pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv')

In [37]:
bmwdf=df[df['Make']=='BMW']
bmwdf['MSRP'].mean()

61546.76347305389

## Question 4 Cars having missing Engine hp values

In [38]:
df

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [39]:
cars_2015=df[df['Year']>=2015]

In [40]:
cars_2015['Engine HP'].isnull().sum()

51

## 51 Missing values in engine hp

# Question 5 mean value

In [41]:
mean_hp_before=df['Engine HP'].mean()

In [42]:
mean_hp_before

249.38607007176023

In [43]:
df['Engine HP']=df['Engine HP'].fillna(mean_engine_hp_before)

In [44]:
mean_hp_after=df['Engine HP'].mean()
print(mean_engine_hp_after)

249.38607007176


In [45]:
print(round(mean_hp_before))
print(round(mean_hp_after))

249
249


## Question 6

In [47]:
df['Make'].unique()

array(['BMW', 'Audi', 'FIAT', 'Mercedes-Benz', 'Chrysler', 'Nissan',
       'Volvo', 'Mazda', 'Mitsubishi', 'Ferrari', 'Alfa Romeo', 'Toyota',
       'McLaren', 'Maybach', 'Pontiac', 'Porsche', 'Saab', 'GMC',
       'Hyundai', 'Plymouth', 'Honda', 'Oldsmobile', 'Suzuki', 'Ford',
       'Cadillac', 'Kia', 'Bentley', 'Chevrolet', 'Dodge', 'Lamborghini',
       'Lincoln', 'Subaru', 'Volkswagen', 'Spyker', 'Buick', 'Acura',
       'Rolls-Royce', 'Maserati', 'Lexus', 'Aston Martin', 'Land Rover',
       'Lotus', 'Infiniti', 'Scion', 'Genesis', 'HUMMER', 'Tesla',
       'Bugatti'], dtype=object)

In [48]:
rolls_df=df[df['Make']=='Rolls-Royce']

In [50]:
rolls_df=rolls_df[['Engine HP', 'Engine Cylinders', 'highway MPG']]
rolls_df

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5276       563.0              12.0           21
5277       563.0              12.0           21
5278       563.0              12.0           21
5279       563.0              12.0           20
5280       563.0              12.0           20
5281       563.0              12.0           21
5282       563.0              12.0           21
5283       563.0              12.0           21
5284       563.0              12.0           21
7443       322.0              12.0           15
7444       322.0              12.0           15
7553       453.0              12.0           19
7554       453.0              12.0           19
7555       453.0              12.0           19
7556       453.0              12.0           19
7557       453.0              12.0           19
7558       453.0              12.0           19
7559       453.0              12.0           19
7560       453.0              12.0           19
7561       453.0              12.0           19
7562       453.0              12.0           19
7563       453.0              12.0           19
7564       453.0              12.0           19
9431       322.0              12.0           15
9432       322.0              12.0           15
11448      624.0              12.0           21
11449      624.0              12.0           21
11450      624.0              12.0           21

In [52]:
rolls_df=rolls_df.drop_duplicates()

In [112]:
X=np.array([rolls_df])

In [113]:
X=X[0]
X.shape

(7, 3)

In [114]:
XT=X.transpose()
XT.shape

(3, 7)

In [98]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [115]:
XTX=matrix_matrix_multiplication(XT,X)

In [116]:
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [117]:
Xs_inv = np.linalg.inv(XTX)

In [118]:
Xs_inv.sum()

0.032212320677486195

In [121]:
XT.shape

(3, 7)

## Question 7 

In [127]:
y=np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

In [130]:
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [138]:
Xnew=matrix_matrix_multiplication(Xs_inv,XT)

In [144]:
w=Xnew.dot(y)

In [145]:
w

array([ 0.19989598, 31.02612262, 31.65378877])

In [111]:
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [124]:
Xnew.shape

(3, 7)